spring.application.name=my-market-app
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=jdbc:postgresql://localhost:5433/market_db
spring.liquibase.user=postgres
spring.liquibase.password=password

spring.r2dbc.url=r2dbc:postgresql://localhost:5433/market_db
spring.r2dbc.username=postgres
spring.r2dbc.password=password

server.port = 8089

spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.contexts=dev
spring.webflux.hiddenmethod.filter.enabled=true


spring.data.redis.host=localhost
spring.data.redis.port=6379

app.redis.key.item=item:
app.redis.key.img=item:img:
app.redis.key.idx.price=idx:items:price
app.redis.key.idx.alpha=idx:items:alpha
app.redis.key.idx.word=idx:word:

items.cart.cache = items:cart

items.cart.time.cache = 6
items.cart.time.cache.main = 6

app.services.payment.url=http://localhost:8081

spring.session.store-type: redis


spring.security.oauth2.client.registration.my-client.client-id=shop-client
spring.security.oauth2.client.registration.my-client.client-secret=fpsuzjNkSym7pdeyqA1AZrSLVeQ2WjZG
spring.security.oauth2.client.registration.my-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.my-client.issuer-uri=http://localhost:8080/realms/shop-realm

#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.com.b0cka=DEBUG