spring.application.name=my-market-app
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=jdbc:postgresql://localhost:5432/my-market-app
spring.liquibase.user=postgres
spring.liquibase.password=postgres

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/my-market-app
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.contexts=dev


spring.webflux.hiddenmethod.filter.enabled=true


