spring.application.name=my-market-app
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=jdbc:postgresql://db:5432/my-market-app
spring.liquibase.user=postgres
spring.liquibase.password=postgres

spring.r2dbc.url=r2dbc:postgresql://db:5432/my-market-app
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres


spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.contexts=dev
spring.webflux.hiddenmethod.filter.enabled=true


spring.data.redis.host=localhost
spring.data.redis.port=6379

app.redis.key.item=item:
app.redis.key.img=item:img:
app.redis.key.idx.price=idx:items:price
app.redis.key.idx.alpha=idx:items:alpha
app.redis.key.idx.word=idx:word:

items.cart.time.cache = 6
items.cart.time.cache.main = 6